name = "elderscape-modelviewer"
main = "workers/ai-editor.ts"
compatibility_date = "2025-10-28"

[vars]
AI_GATEWAY = "pick-of-gods"

[[kv_namespaces]]
binding = "KV_BINDING"
id = "45b66378f5774ce78787331834db0496"

[[d1_databases]]
binding = "DB"
database_id = "dfcdb955-f128-4294-aa8e-2e05a33221f0"
database_name = "elderscape-d1"

[ai]
binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true
